#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0 > /dev/null 2>&1

runApplication blockMesh

cp 0/alpha1.org 0/alpha1

runApplication setFields

runApplication `getApplication`
