#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso phaseEquationsOfState
wmake
wmake compressibleInterDyMFoam

# ----------------------------------------------------------------- end-of-file
