#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in heater leftSolid rightSolid
do
   rm -f 0*/$i/{rho,mut,alphat,epsilon,k,U,p_rgh,Qr,G,IDefault}
done

for i in bottomAir topAir heater leftSolid rightSolid
do
    changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


for i in bottomAir topAir
do
    faceAgglomerate -region $i -dict constant/viewFactorsDict > log.faceAgglomerate.$i 2>&1
done

for i in bottomAir topAir
do
    viewFactorsGen -region $i > log.viewFactorsGen.$i 2>&1
done



#-- Run on single processor
runApplication `getApplication`

## Run in parallel
## Decompose
#runApplication decomposePar -allRegions
#
#for i in bottomAir topAir
#do
#    mpirun -np 4 faceAgglomerate -region $i -dict constant/viewFactorsDict -parallel>   log.faceAgglomerate.$i 2>&1
#done

#for i in bottomAir topAir
#do
#    mpirun -np 4 viewFactorsGen -region $i -parallel > log.viewFactorsGen.$i 2>&1
#done

## Run
#runParallel `getApplication` 4
#
## Reconstruct
#runApplication reconstructPar -allRegions


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
