#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

foamCleanTutorials cases
rm -rf 0/alpha[1-3] 0/alpha[1-3].gz

# ----------------------------------------------------------------- end-of-file
