#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp 0/alpha1.org 0/alpha1
cp 0/alpha2.org 0/alpha2
cp 0/alpha3.org 0/alpha3
runApplication setFields
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
