#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface
\rm -f constant/triSurface/wigley-scaled-oriented.stl.gz

cleanCase
rm 0/alpha1.gz 0/cellLevel.gz 0/pointLevel.gz constant/polyMesh/boundary \
    > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
