#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType incompressible
wmake $makeType interfaceProperties
wmake $makeType twoPhaseInterfaceProperties
# wmake $makeType compressible

# ----------------------------------------------------------------- end-of-file
