#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake libo postCalc
wmake $makeType foamCalcFunctions

functionObjects/Allwmake $*

# ----------------------------------------------------------------- end-of-file
